sudo: required #is required to use docker service in travis

language: bash 

env:
  global:
    - secure: SdjEWGZL04raCAwmyQ8NYTMjGWGySYfw3h+Jhw7yHd5n4xo0LuomQDgC7hs1CMbQ4WvEtw01TlqxesK0xquwYR/13Q382fX38LdBfUegOtUJMFBsBzMdLRJC2fjyb/5mmcI1GfRzHuTrSDYHekmduDRT++V3qnMoGRj9bxb0OSIjqwqNMqGaUCMUc6KzWzi/UPHcmf8//fgfQAOUFetD/LKRtvcFJEBlpuML0tGK4kzZDt3WTAiIboQMAcgM5UGL5nFq007bb3DKC83zInCOmKoGovlVeu2dii5/WYAUVrAXIWPuT9g+n0A7cpGXjH6x7ufgglW7oe4fe5w4nakKKA4Xtu2PQ67VSotSOr9C6ZOq05RtMmy/NuAU8q3BuUzjeG0zgy1jxLpDzp3CUI+2fUsOB17dCwhN674yaEm1nmKYoqYeLTlrTPocU+4SbC90BKAEpFN7RhrLG236GwmAvVLY52CU2T5yCV6Ygi9gCvpVDzDjd7NJsbV66A9AISs98vLdt50JSey5p/4XdeoNN50DRJ/Zoy+U1KH/PN4gWhDD0UhyuSAq/rYVqPvnBeGnrQCbLdMunomCvAzyQSHkIhT5u3mUpUVW7aSWvOQkodfhDSqilk4PFD8ZKWaol14iURYVzbY6FjrRfrLRnZXztTJiECg6rPZrue2KtU/Zuz8= # DOCKER_MAIL
    - secure: L5aWUGoRa5av416n073A+x5rWr0iNeBVO8CjVevQuP6k1vYODwShbWVbgGQ6UL2THnxMh795Rxq1MRwq1arxEwtfUE3Pv8uy+yAXkkHWh7ghmPFB6+MDTqO5N0B4D2MPvn5xa8ukAJW+l0E9vuB97MqBEbyv18LXuVTNO+yLC9PrYXwkxb7n4xUX/TwuRBedILDf4AaWPZby65K9mdXgZvjk/PEtSqugbDkdTZgOEyp+kpGQYemNlFNxrDPGImp+uyX9o1P+eDFaY25eC+cGBct8zw/0p2nhgb/+qJfwIqtKzg6uy6JOA+7ZeG8UeK8Vv8WtjkiGGqlazeUXncY7UANugC2KJYVHbx/Bmtdokys/zDXEmgrty2QXJYifVH+KxyIDUtebvuX/PVXDWyPDK53FY8wqoCgLtNvVG/xKxNw/yZUeI2BERXI2q0cDw0s6Xi7HhkIAN3gs6UQMU2sJt+aS7R9l9KKQgEVWhJic4nfkpBsmnMcbRSOIQEOmnewUKafkFSTfJ2oASJGgkz/f4clq5S82lFd0i+qwT5+1eupVY6JtGcPfUtyEtdW2mFqG0jPE5kfjBFw5MpCyUDNmKXmZiKl4BfE3TMRB/NjzBkDWMTTpBU0U5g1X6NRzsGeYSX3bgMXfx0DGL27aBerNDsR7Gc5UnTqX+vl/r1K5S84= # DOCKER_USER
    - secure: Go8TAJDYAopWhYBs/dMPWj3xGyvZUo6z0I6UOL+qS52L1lxE2g1wwvwxEUzYyb+c0XLGgHjkco0r3lVkbe5QbK3mEn095QdLOnX9NqDMeHLjg9l8EglIWWNAWRemdCHck1pwjpYK9JSgCK9rKgvGR1GyEr/NObwLqcoGhk9qm6QBtNih+j09ZBMbWHNqXj94LHuK3cX6Tp1h8gfQY0G2FhaDIA3B0BjFvGHnac9xQ/FDzOZlqxjE6BuXyXOixgRYeVF0JKVzc1Yd0jpPqBaYG/h21WA3/DzOX0VoM7xOpPrSJKyUOl1nm/LJM5jXJ7zM9ca+bMS4iGCC1VfActZ7Fvb2CrpxN99Pc1/eay/wE53YX1PJHIqRDFi8JhEz/SZ8tsNyzUx0VuPOHjBnFG+hPvv3VtAhfMtFdL0D4LRrOjG6WQnQedUFSsLGDLnysUw/EUpMEx0A8gnOQ7eVzn01NDIQKcG+jdZU1/W24Pq+D9PdFR7Ojz94HNA1H/KorBpGeBus1sKB5xB+mSZgvFxL2NA/RdFiVby/u9BrG6wRvroTJYDCXr7cSi7S2EbhpJn8+okdD6dAzoIkbrZMvE7oIWGJxiwebQFricavlQBFqFQUklPCklZf98OgpCTN5Gzsd2ie2v8Ju9pLDlIJmbLTKMosCRCAooIgoYczqmjnvyI= # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}


services: 
  - docker # required, but travis uses older version of docker :(

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - docker --version  # document the version travis is using
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build images
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO_VLC=sego/vlc-nox-pi
  #- docker build -t sego/aceproxy-pi:$COMMIT ./aceproxy
  - docker build -t $REPO_VLC:$COMMIT ./vlc
  #- docker build -t sego/acestream-pi:$COMMIT ./acestream
  
  # push
  - echo $REPO_VLC:$COMMIT
  - echo $TRAVIS_BUILD_NUMBER
  - docker tag $REPO_VLC:$COMMIT $REPO_VLC:$TAG
  - docker tag $REPO_VLC:$COMMIT $REPO_VLC:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO_VLC


  
# sadly, travis doesn't cache docker builds yet, so each build will take a while
