sudo: required #is required to use docker service in travis

language: bash 

services: 
  - docker # required, but travis uses older version of docker :(

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - docker --version  # document the version travis is using
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build images
  - docker build -t aceproxy-pi ./aceproxy
  - docker build -t vlc-pi ./vlc

after_success:
  
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path

  
# sadly, travis doesn't cache docker builds yet, so each build will take a while
